<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DEV_TEST_JOYDIP" name="field_validation.C_Reg_page_Validation" tests="9" failures="1" timestamp="07 Dec 2018 05:40:19 GMT" time="152.599" errors="0">
  <testcase name="C_Reg_PassWord_Validation" time="23.724" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Mobileno_Validation" time="10.854" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Fname_Validation" time="9.944" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Lname_Validation" time="10.303" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Username_Validation" time="24.586" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Email_Validation" time="25.436" classname="field_validation.C_Reg_page_Validation">
    <skipped/>
  </testcase> <!-- C_Reg_Email_Validation -->
  <testcase name="C_Reg_Email_Validation" time="10.371" classname="field_validation.C_Reg_page_Validation">
    <skipped/>
  </testcase> <!-- C_Reg_Email_Validation -->
  <testcase name="C_Reg_Mname_Validation" time="10.181" classname="field_validation.C_Reg_page_Validation"/>
  <testcase name="C_Reg_Email_Validation" time="27.200" classname="field_validation.C_Reg_page_Validation">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at field_validation.C_Reg_page_Validation.C_Reg_Email_Validation(C_Reg_page_Validation.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- C_Reg_Email_Validation -->
</testsuite> <!-- field_validation.C_Reg_page_Validation -->
